# Общие конфигурации

# Колонки датафрейма транзакций
txns_df:
  client_id: int64
  txn_time: datetime64[ns]
  unix_time: int64
  amount: float64
  type: str
  channel: str
  category: str
  online: bool
  merchant_id: int64
  trans_city: str
  trans_lat: float64
  trans_lon: float64
  trans_ip: str
  device_id: int64
  account: int64
  is_fraud: bool
  is_suspicious: bool
  status: str
  rule: str

# Пути к данным
data_paths:
  cleaned_data:
    clients_sample: "./data/cleaned_data/clients_sample.gpkg"
    offline_merchants: "./data/cleaned_data/offline_merchants_points.gpkg"
    online_merchant_ids: "./data/cleaned_data/online_merchant_ids.csv"
    client_devices: "./data/cleaned_data/client_devices.csv"
    fraud_devices: "./data/cleaned_data/fraud_devices.csv"
    districts_ru: "./data/cleaned_data/district_ru.gpkg"
    area_centers: "./data/cleaned_data/area_centers.gpkg"
    clients_with_geo: "./data/cleaned_data/clients_with_geo.gpkg"
    fraud_ips: "./data/cleaned_data/fraud_ips.gpkg"
    cat_stats_full: "./data/cleaned_data/cat_stats_full.csv"
    cat_fraud_amts: "./data/cleaned_data/cat_fraud_amts.csv"
    drop_purch_cats: "./data/cleaned_data/drop_purch_cats.csv"

  generated_data:
    timestamps: "./data/generated_data/timestamps.parquet"
    legit_txns: "./data/generated_data/legit_trans_148K.parquet"
    accounts_default: "./data/generated_data/accounts_default.csv"
    accounts: "./data/generated_data/accounts.csv"
    outer_accounts: "./data/generated_data/outer_accounts.csv"
    dist_drops: "./data/generated_data/dist_drops.gpkg"
    purchase_drops: "./data/generated_data/purchase_drops.gpkg"
