# Общие конфигурации

validator: # Параметры валидации конфигов
  rates: # Валидация fraud rate-ов
    # Допустимый процент ошибки при расчете макс. кол-ва возможных лег. транз-ций
    # Вероятность, что транз-ций сгенерируется больше расчитанного макс. возможного числа
    overflow_prob: 0.001 

# Префикс для названия папок под хранение данных каждого запуска генератора
run_prefix: "generation_run_" 


# Колонки датафрейма транзакций
txns_df:
  client_id: int64
  txn_time: datetime64[ns]
  unix_time: int64
  amount: float64
  type: str
  channel: str
  category: str
  online: bool
  merchant_id: int64
  trans_city: str
  trans_lat: float64
  trans_lon: float64
  trans_ip: str
  device_id: int64
  account: int64
  is_fraud: bool
  is_suspicious: bool
  status: str
  rule: str

# Пути к данным
data_paths:
  base:
    accounts: "./data/base/accounts.csv"
    accounts_default: "./data/base/accounts_default.csv"
    cat_stats_full: "./data/base/cat_stats_full.csv"
    category_stats: "./data/base/category_stats.csv"
    city_centers: "./data/base/city_centers.gpkg"
    client_devices: "./data/base/client_devices.csv"
    cities: "./data/base/cities.gpkg"
    offline_merchants: "./data/base/offline_merchants_points.parquet"
    online_merchant_ids: "./data/base/online_merchant_ids.csv"
    outer_accounts: "./data/base/outer_accounts.csv"

  base_fraud:
    cat_fraud_amts: "./data/base_fraud/cat_fraud_amts.csv"
    drop_purch_cats: "./data/base_fraud/drop_purch_cats.csv"
    fraud_devices: "./data/base_fraud/fraud_devices.csv"
    fraud_ips: "./data/base_fraud/fraud_ips.parquet"
    rules: "./data/base_fraud/rules.csv"

  cleaned:
    clients: "./data/cleaned/client_df_clean.csv"
    districts: "./data/cleaned/district_df_clean.csv"

  clients:
    clients: "./data/clients/clients.parquet"
    legit_clients: "./data/clients/legit_clients.parquet"
    dist_drops: "./data/clients/dist_drops.parquet"
    purchase_drops: "./data/clients/purchase_drops.parquet"

  generated:
    legit_txns: "./data/generated/latest/legit_txns.parquet"
    compr_client_txns: "./data/generated/latest/compr_client_txns.parquet"
    dist_drop_txns: "./data/generated/latest/dist_drop_txns.parquet"
    purch_drop_txns: "./data/generated/latest/purch_drop_txns.parquet"
    all_txns: "./data/generated/latest/all_txns.parquet"
    history: "./data/generated/history"
    latest: "./data/generated/latest/"

# названия папок и файлов
data_storage:
  files:
    all_txns: "all_txns.parquet"
