# Настройки для сумм входящих транзакций
inbound_amt: 
  low: 5000
  high: 100000
  mean: 30000
  std: 20000

# Настройки дроп фрода связанного с потоком денег - получение и перевод/снятие - дроп-распределитель
distributor:
  in_lim: 6 # лимит входящих транзакций. После его достижения - отклонение всех операций клиента
  out_lim: 8 # лимит исходящих транзакций. После его достижения - отклонение всех операций клиента
  period_in_lim: 2 # Количество входящих транзакций после которых дроп уходит на паузу.
  period_out_lim: 5 # Количество исходящих транзакций после которых дроп уходит на паузу.
  round: 100 # Округление целой части сумм транзакций. Напр. 500 значит что суммы будут кратны 500 - кончаться на 500 или 000
  split_rate: 0.7 # Доля случаев когда дроп распределяет деньги по частям
  chunks: # Настройки создания суммы, для распределения полученных денег по частям
    atm_min: 10000 # Минимальная сумма для снятий в банкомате.
    atm_share: # Доля от баланса, которую дроп снимает в случае снятия в банкомате
      min: 0.3
      max: 0.7
    step: 1000 # Шаг возможных сумм. Чем меньше шаг, тем больше вариантов.
    rand_rate: 0.9 # В скольких случаях размер суммы должен быть семплирован, а не взят размер предыдущей транзакции
    rcvd_small: # Категория полученной дропом суммы
      limit: 10000 # Категория все что "до" включительно
      min: 3000 # # Минимальная сумма чанка для этой категории
      max: 10000 # Максимальная сумма чанка для этой категории
    rcvd_medium:
      limit: 30000
      min: 5000
      max: 25000
    rcvd_large: # порог не прописываем, т.к. это все что выше medium
      min: 10000
      max: 40000
  # лимиты на перевод. Если баланс больше. То разбиваем на части
  trf_max: 40000
  reduce_share: 0.25 # Доля от суммы первой откл. транз. для уменьшения след. транз-ций
  to_drops:
    rate: 0.1 # Доля исходящих транзакций другим дропам.
    min_drops: 6 # Минимальное число дропов в accounts для возможности отправки
                  # переводов другим дропам.
  crypto_rate: 0.1 # Доля переводов в крипту от переводов дропа
  attempts: # Лимиты попыток операций после первой отклоненной операции
    trf_min: 0 # Перевод
    trf_max: 3
    atm_min: 0 # Снятие
    atm_max: 2
  data_storage:
    # Ключ к полному пути записи файла в папке data/generated/latest/ в base.yaml
    key_latest: "dist_drop_txns"
    # Ключ к директории для создания отдельной папки генерации в в base.yaml
    key_history: "history"
    # Ключ к категории директорий в base.yaml. Тут будут храниться данные
    category: "generated" 
    # Название индивидуальной папки внутри папки текущего запуска генерации
    folder_name: "dist_drops" 
    files:
      txns: "dist_drop_txns.parquet"
      clients: "dist_drops.parquet"
  

# Настройки дроп фрода связанного с отмыванием поступающих денег через покупки
purchaser:
  in_lim: 6 # лимит входящих транзакций. После его достижения - отклонение всех операций клиента
  out_lim: 8 # лимит исходящих транзакций. После его достижения - отклонение всех операций клиента
  period_in_lim: 2 # Количество входящих транзакций после которых дроп уходит на паузу.
  period_out_lim: 5 # Количество исходящих транзакций после которых дроп уходит на паузу.
  round: 100 # Округление целой части сумм транзакций. Напр. 500 значит что суммы будут кратны 500 - кончаться на 500 или 000
  split_rate: 0.7 # Доля случаев когда дроп распределяет деньги по частям
  chunks: # Настройки создания суммы, для распределения полученных денег по частям
    # atm_min: 0 # для этого типа дропа это значение нужно оставить в виде заглушки.
    step: 1000 # Шаг возможных сумм. Чем меньше шаг, тем больше вариантов.
    rand_rate: 0.9 # В скольких случаях размер суммы должен быть семплирован, а не взят размер предыдущей транзакции
    rcvd_small: # Категория полученной дропом суммы
      limit: 10000 # Категория "все что до" включительно
      min: 3000 # Мин. сумма чанка для этой категории
      max: 10000 # Макс. сумма чанка для этой категории
    rcvd_medium:
      limit: 30000
      min: 5000
      max: 25000
    rcvd_large: # порог не прописываем, т.к. это все что выше medium
      min: 10000
      max: 40000
  # лимиты на одну покупку. Если баланс больше. То разбиваем на части
  amt_max: 40000
  reduce_share: 0.25 # Доля от суммы первой откл. транз. для уменьшения след. транз-ций
  attempts: # Лимиты попыток операций после первой отклоненной операции
    min: 0
    max: 3
  data_storage:
    # Ключ к полному пути записи файла в папке data/generated/latest/ в base.yaml
    key_latest: "purch_drop_txns"
    # Ключ к директории для создания отдельной папки генерации в в base.yaml
    key_history: "history"
    # Ключ к категории директорий в base.yaml. Тут будут храниться данные
    category: "generated"  
    # Название индивидуальной папки внутри папки текущего запуска генерации
    folder_name: "purch_drops"
    files:
      txns: "purch_drop_txns.parquet"
      clients: "purchase_drops.parquet"


time: 
  # Интервал для паузы в активности дропа в минутах. Для больших пауз. Например дроп закончил активность до следующего дня.
  # Прибавляется ко времени первой транзакции из последнего периода активности
  lag_interval: 1440
  # Минимум и максимум случайной дельты времени в минутах. Для случаев когда дельта может быть <= 0 и > 0.
  # Эта дельта прибавляется к lag_interval, чтобы рандомизировать время возобновления активности,
  # чтобы оно не было ровным.
  two_way_delta:
    min: -180
    max: 180
  # Минимум и максимум случайной дельты времени в минутах. Для случаев когда дельта может быть только > 0.
  # Эта дельта - промежуток между транзакциями дропа в одном периоде. Просто прибавляется ко времени последней транзакции.
  pos_delta:
    min: 30
    max: 180