purchase_fraud: 
  rate: 0.7 # процент от всего фрода

# Настройки дроп фрода связанного с потоком денег - получение и перевод/снятие 
drop_distributor:
  rate: 0.15 # процент от всего фрода
  in_lim: 6 # лимит входящих транзакций. После его достижения - отклонение всех операций клиента
  out_lim: 8 # лимит исходящих транзакций. После его достижения - отклонение всех операций клиента
  period_in_lim: 2 # Количество входящих транзакций после которых дроп уходит на паузу.
  period_out_lim: 5 # Количество исходящих транзакций после которых дроп уходит на паузу.

# Интервал для паузы в активности дропа в минутах. Для больших пауз. Например дроп закончил активность до следующего дня.
# Прибавляется ко времени первой транзакции из последнего периода активности
lag_interval: 1440

# Минимум и максимум случайной дельты времени в минутах. Для случаев когда дельта может быть <= 0 и > 0.
# Эта дельта прибавляется к lag_interval, чтобы рандомизировать время возобновления активности,
# чтобы оно не было ровным.
two_way_delta:
  min: -180
  max: 180

# Минимум и максимум случайной дельты времени в минутах. Для случаев когда дельта может быть только > 0.
# Эта дельта - промежуток между транзакциями дропа в одном периоде. Просто прибавляется ко времени последней транзакции.
pos_delta:
  min: 30
  max: 180

# Настройки дроп фрода связанного с отмыванием поступающих денег через покупки
drop_purchaser:
  rate: 0.15  # процент от всего фрода