# Конфигурации для фрода.
# Общие параметры и специфичные для фрода в покупках.
# Для дропов их конфиги в drops.yaml

fraud_rates: 
  total: 0.01 # доля фрода от всех транзакций
  # Ниже по типам фрода доли от всего фрода 
  compr_client: 0.7 # фрод с компрометацией данных/аккаунтов клиентов.
  drops:
    distributor: 0.15 # дропы которые переводят и снимают полученные деньги
    purchaser: 0.15 # дропы которые покупают товары на полученные деньги

purchase: # конфигурация сумм фрода с компрометацией данных/аккаунтов клиентов.
  amount: # распределение сумм
    extreme: # Категории по которым возможен фрод на очень большие суммы
      categories: ['shopping_pos', 'shopping_net', 'entertainment', 'misc_pos', 'misc_net', 'travel']
      low: 1000
      high: 60000
      mean: 20000
      std: 20000
    other: # Остальные категории
      low: 500
      high: 8000
      mean: 4000
      std: 1000
