# Конфигурации для фрода

fraud_rate: 0.01 # процент фрода от всех транзакций

purchase_fraud: 
  rate: 0.7 # процент от всего фрода

# Настройки дроп фрода связанного с потоком денег - получение и перевод/снятие 
drop_flow_cashout:
  rate: 0.15 # процент от всего фрода
  in_lim: 6 # лимит входящих транзакций. После его достижения - отклонение всех операций клиента
  out_lim: 8 # лимит исходящих транзакций. После его достижения - отклонение всех операций клиента

# Настройки дроп фрода связанного с отмыванием поступающих денег через покупки
drop_purchase_cashout:
  rate: 0.15  # процент от всего фрода
  
