# Конфиги для генерации легальных транзакций


time:
  # минимальные интервалы времени между транзакциями в минутах для функции
  # check_min_interval_from_near_txn. См. docstring функции для деталей.
  min_intervals: 
    offline_time_diff: 60 # между оффлайн
    online_time_diff: 6 # мин. разница между онлайн транз.
    online_ceil: 60 # макс. разница от последней онлайн транз. если текущая онлайн.
    general_diff: 30 # мин. разница между онлайн и оффлайн транз.
    general_ceil: 90 # макс. разница от последней транз. если online значения разные


txn_num: # настройки кол-ва транзакций.
  total_txns: 1000 # Сколько примерно транзакций сгенерировать
  avg_txn_num: 50 # Среднее кол-во на клиента
  txn_num_std: 10 # Стандартное откл. кол-ва транзакций на клиента
  low_bound: 1 # мин. транз-ций на клиента
  up_bound: 120 # макс. транз-ций на клиента


in_chunks_gen: # Параметры записи транзакций чанками в файлы.
  chunk_size: 200 # Размер чанка.

data_storage:
  # Ключ к полному пути записи файла в папке data/generated/latest/ в base.yaml
  key_latest: "legit_txns"
   # Ключ к пути для создания отдельной папки генерации в в base.yaml
  key_history: "history"
  # Ключ к категории директорий в base.yaml. Тут будут храниться данные
  category: "generated" 
  # Префикс для названия индивидуальной папки внутри category
  prefix: "legit_"
