# Конфиги для генерации легальных транзакций

time:
  # минимальные интервалы времени между транзакциями в минутах для функции
  # check_min_interval_from_near_trans
  min_intervals: 
    offline_time_diff: 60 # между оффлайн
    online_time_diff: 6 # мин. разница между онлайн транз.
    online_ceil: 60 # макс. разница от последней онлайн транз. если текущая онлайн.
    general_diff: 30 # мин. разница между онлайн и оффлайн транз.
    general_ceil: 90 # макс. разница от последней транз. если online значения разные